// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cinema.log.server.Models;

#nullable disable

namespace cinema.log.server.Repositories.Migrations
{
    [DbContext(typeof(CinemaLogContext))]
    [Migration("20250101102247_UpgradeA")]
    partial class UpgradeA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cinema.log.server.Models.Entities.ComparisonHistory", b =>
                {
                    b.Property<Guid>("ComparisonHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ComparisonDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FilmAFilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilmBFilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasEqual")
                        .HasColumnType("bit");

                    b.Property<Guid?>("WinningFilmFilmId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ComparisonHistoryId");

                    b.HasIndex("FilmAFilmId");

                    b.HasIndex("FilmBFilmId");

                    b.HasIndex("UserId");

                    b.HasIndex("WinningFilmFilmId");

                    b.ToTable("ComparisonHistories");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.Film", b =>
                {
                    b.Property<Guid>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ProfilePicUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.UserFilmRating", b =>
                {
                    b.Property<Guid>("UserFilmRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("EloRating")
                        .HasColumnType("real");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("InitialRating")
                        .HasColumnType("real");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfComparisons")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserFilmRatingId");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFilmRatings");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.ComparisonHistory", b =>
                {
                    b.HasOne("cinema.log.server.Models.Entities.Film", "FilmA")
                        .WithMany()
                        .HasForeignKey("FilmAFilmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("cinema.log.server.Models.Entities.Film", "FilmB")
                        .WithMany()
                        .HasForeignKey("FilmBFilmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("cinema.log.server.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cinema.log.server.Models.Entities.Film", "WinningFilm")
                        .WithMany()
                        .HasForeignKey("WinningFilmFilmId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FilmA");

                    b.Navigation("FilmB");

                    b.Navigation("User");

                    b.Navigation("WinningFilm");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.Review", b =>
                {
                    b.HasOne("cinema.log.server.Models.Entities.Film", null)
                        .WithMany("Reviews")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cinema.log.server.Models.Entities.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.UserFilmRating", b =>
                {
                    b.HasOne("cinema.log.server.Models.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cinema.log.server.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.Film", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("cinema.log.server.Models.Entities.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
